gcc main.c render.c input.c -o debuggy
./debuggy
Hello World
NAME: [Lid Switch]
NAME: [Power Button]
NAME: [AT Translated Set 2 keyboard]
NAME: [Video Bus]
NAME: [Intel HID events]
NAME: [Intel HID 5 button array]
NAME: [PC Speaker]
NAME: [Dell Privacy Driver]
NAME: [Dell WMI hotkeys]
NAME: [VEN_27C6:00 27C6:0D43 Mouse]
NAME: [VEN_27C6:00 27C6:0D43 Touchpad]
NAME: [PS/2 Generic Mouse]
NAME: [keyd virtual keyboard]
NAME: [keyd virtual pointer]
NAME: [HDA Intel PCH Mic]
NAME: [HDA Intel PCH Headphone]
NAME: [HDA Intel PCH HDMI/DP,pcm=3]
NAME: [HDA Intel PCH HDMI/DP,pcm=7]
NAME: [HDA Intel PCH HDMI/DP,pcm=8]
NAME: [HDA Intel PCH HDMI/DP,pcm=9]
NAME: [LOGI M240 Mouse]
NAME: [Lid Switch]
NAME: [Power Button]
NAME: [AT Translated Set 2 keyboard]
NAME: [Video Bus]
NAME: [Intel HID events]
NAME: [Intel HID 5 button array]
NAME: [PC Speaker]
NAME: [Dell Privacy Driver]
NAME: [Dell WMI hotkeys]
NAME: [VEN_27C6:00 27C6:0D43 Mouse]
NAME: [VEN_27C6:00 27C6:0D43 Touchpad]
NAME: [PS/2 Generic Mouse]
NAME: [keyd virtual keyboard]
NAME: [keyd virtual pointer]
NAME: [HDA Intel PCH Mic]
NAME: [HDA Intel PCH Headphone]
NAME: [HDA Intel PCH HDMI/DP,pcm=3]
NAME: [HDA Intel PCH HDMI/DP,pcm=7]
NAME: [HDA Intel PCH HDMI/DP,pcm=8]
NAME: [HDA Intel PCH HDMI/DP,pcm=9]
NAME: [LOGI M240 Mouse]
rm ./debuggy
